### ISSUE TITLE
Not able to set 'smtp_generic_map_entries' in postfix

### ISSUE THREAD

**Issue by marutinandanpandya** [sous-chefs/postfix#153]
### Cookbook version
[5.3.1]

### Chef-client version
[12.6.0]

### Platform Details
[CentOs 7.3]

### Scenario:
Trying to install postfix 2.10.1-6.el7 and change outgoing SMTP email( trying to use smtp_generic_map_etries) 

### Steps to Reproduce:
Berksfile
```
source 'https://api.berkshelf.com'
metadata
cookbook 'postfix'
```

.kitchen.yml
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.6.0
  roles_path: "test/integration/roles"

platforms:
  - name: centos-7.3

suites:
  - name: mail-postfix
    run_list:
      - recipe[install_postfix]
```

attributes/postfix.rb
```
override['postfix']['main'] = {
  'inet_protocols'     => 'ipv4',
  'relayhost'          => 'mail.ops.example.net',
  'mydomain'           => 'example.net',
  'myorigin'           => 'example.net'
}
override['postfix']['smtp_generic_map_entries'] = { 
	"root@youinternaldomain.local" => "admin@example.com", 
	"admin@youinternaldomain.local" => "admin@example.com" 
}
```
recipe/postfix.rb
```
package 'postfix' do
  action [:install, :upgrade]
  version '2.10.1-6.el7'
end
```

running kitchen-test converge should install postfix on vagrant.

### Expected Result:
1. It should create /etc/postfix/generic file with 'root@youinternaldomain.local' 2. 'admin@youinternaldomain.local' entries along with **smtp_generic_maps = hash:/etc/postfix/generic** in main.cf

### Actual Result:
1. /etc/postfix/generic is default with no changes
2. no **smtp_generic_maps = hash:/etc/postfix/generic** in main.cf
